### ISSUE TITLE
brew install failed

### ISSUE THREAD

**Issue by NeoChow** [stepanhruda/ios-simulator-app-installer#28]
```
 $ brew install ios-simulator-app-installer
==> Installing ios-simulator-app-installer from stepanhruda/ios-simulator-app-installer
==> Cloning https://github.com/stepanhruda/ios-simulator-app-installer.git
Updating /Library/Caches/Homebrew/ios-simulator-app-installer--git
==> Checking out revision 532a8ed86388e5080fcadf176ba55a0f9fc2d237
==> make
Last 15 lines from /Users/neochow/Library/Logs/Homebrew/ios-simulator-app-installer/01.make:
Ditto /Users/neochow/Desktop/untitled\ folder/ios-simulator-app-installer-emfivnkbwshoowbudnxihttbjmxk/Build/Intermediates/ArchiveIntermediates/ios-simulator-app-installer/BuildProductsPath/Release/ios_simulator_app_installer.swiftmodule/x86_64.swiftmodule /Users/neochow/Desktop/untitled\ folder/ios-simulator-app-installer-emfivnkbwshoowbudnxihttbjmxk/Build/Intermediates/ArchiveIntermediates/ios-simulator-app-installer/IntermediateBuildFilesPath/ios-simulator-app-installer.build/Release/ios-simulator-app-installer.build/Objects-normal/x86_64/ios_simulator_app_installer.swiftmodule
    cd /tmp/ios-simulator-app-installer20160408-8078-kzndhb/src
    /usr/bin/ditto -rsrc /Users/neochow/Desktop/untitled\ folder/ios-simulator-app-installer-emfivnkbwshoowbudnxihttbjmxk/Build/Intermediates/ArchiveIntermediates/ios-simulator-app-installer/IntermediateBuildFilesPath/ios-simulator-app-installer.build/Release/ios-simulator-app-installer.build/Objects-normal/x86_64/ios_simulator_app_installer.swiftmodule /Users/neochow/Desktop/untitled\ folder/ios-simulator-app-installer-emfivnkbwshoowbudnxihttbjmxk/Build/Intermediates/ArchiveIntermediates/ios-simulator-app-installer/BuildProductsPath/Release/ios_simulator_app_installer.swiftmodule/x86_64.swiftmodule

Ditto /Users/neochow/Desktop/untitled\ folder/ios-simulator-app-installer-emfivnkbwshoowbudnxihttbjmxk/Build/Intermediates/ArchiveIntermediates/ios-simulator-app-installer/BuildProductsPath/Release/ios_simulator_app_installer.swiftmodule/x86_64.swiftdoc /Users/neochow/Desktop/untitled\ folder/ios-simulator-app-installer-emfivnkbwshoowbudnxihttbjmxk/Build/Intermediates/ArchiveIntermediates/ios-simulator-app-installer/IntermediateBuildFilesPath/ios-simulator-app-installer.build/Release/ios-simulator-app-installer.build/Objects-normal/x86_64/ios_simulator_app_installer.swiftdoc
    cd /tmp/ios-simulator-app-installer20160408-8078-kzndhb/src
    /usr/bin/ditto -rsrc /Users/neochow/Desktop/untitled\ folder/ios-simulator-app-installer-emfivnkbwshoowbudnxihttbjmxk/Build/Intermediates/ArchiveIntermediates/ios-simulator-app-installer/IntermediateBuildFilesPath/ios-simulator-app-installer.build/Release/ios-simulator-app-installer.build/Objects-normal/x86_64/ios_simulator_app_installer.swiftdoc /Users/neochow/Desktop/untitled\ folder/ios-simulator-app-installer-emfivnkbwshoowbudnxihttbjmxk/Build/Intermediates/ArchiveIntermediates/ios-simulator-app-installer/BuildProductsPath/Release/ios_simulator_app_installer.swiftmodule/x86_64.swiftdoc

** ARCHIVE FAILED **


The following build commands failed:
    Ld /Users/neochow/Desktop/untitled\ folder/ios-simulator-app-installer-emfivnkbwshoowbudnxihttbjmxk/Build/Intermediates/ArchiveIntermediates/ios-simulator-app-installer/InstallationBuildProductsLocation/usr/local/bin/ios-simulator-app-installer normal x86_64
(1 failure)
make: *** [ios-simulator-app-installer.xcarchive] Error 65

READ THIS: https://git.io/brew-troubleshooting

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
Validation Failed
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
    from /usr/local/Library/Homebrew/utils.rb:615:in `open'
    from /usr/local/Library/Homebrew/utils.rb:648:in `issues_matching'
    from /usr/local/Library/Homebrew/utils.rb:681:in `issues_for_formula'
    from /usr/local/Library/Homebrew/exceptions.rb:251:in `fetch_issues'
    from /usr/local/Library/Homebrew/exceptions.rb:247:in `issues'
    from /usr/local/Library/Homebrew/exceptions.rb:292:in `dump'
    from /usr/local/Library/brew.rb:134:in `rescue in <main>'
    from /usr/local/Library/brew.rb:29:in `<main>'
```

**Comment by NeoChow** [comment]
I really like this project, but could not go on. And I've search a lot on the internet, but could not work out.

**Comment by stepanhruda** [comment]
I think this will need a fix in the source. Are you on Xcode 7.3 by any chance?

**Comment by NeoChow** [comment]
Yes, I'm using Xcode 7.3 on OS X 10.11.4.   Maybe I should take a look at the source.  : )

**Comment by NeoChow** [comment]
When compiling the ios-simulator-app-installer.xcworkspace in /src with Xcode 7.3, I got the link error exactly like this: https://github.com/lionheart/openradar-mirror/issues/7882. I'll try with Xcode 7.2.1 again, as it'll be OK suggested in the issue.

**Comment by stepanhruda** [comment]
Do you perhaps have any other brew packages installed? They might link swift dylibs into `/usr/local/lib`, which leads to duplicate symbols.

**Comment by stepanhruda** [comment]
Can you try `brew update && brew install stepanhruda/tap/ios-simulator-app-installer`?

**Comment by stepanhruda** [comment]
This works for me on Xcode 7.3, I'm gonna close this. Feel free to reopen if you have issues.
